import {it,expect,vi} from 'vitest';
const loading=vi.hoisted(()=>({pending:null as Promise<ArrayBuffer>|null}));
vi.mock('./dragonfly',()=>({loadDragonfly:async()=>loading.pending??new Uint8Array([0,97,115,109,1,0,0,0]).buffer}));
import {makeBand} from './model';
import {createMixer} from './controller';import {createProject,addTrack} from '../../store/projectModel';import {normalizeMix,withFxView,fxView} from './plugins';
it('failed reverb initialization remains visible and retry waits for confirmed readiness',async()=>{
 const processors:any[]=[];class Node {gain={value:1,setTargetAtTime(){},cancelScheduledValues(){},setValueAtTime(){},linearRampToValueAtTime(){}};pan={value:0,setTargetAtTime(){}};fftSize=2048;smoothingTimeConstant=0;connect(){}disconnect(){}addEventListener(){}getFloatFrequencyData(a:Float32Array){a.fill(-100);}}
 class Worklet extends Node {name:string;messages:any[]=[];port={onmessage:null as any,postMessage:(m:any)=>this.messages.push(m),close(){}};constructor(_c:any,name:string){super();this.name=name;processors.push(this);}}
 vi.stubGlobal('AudioWorkletNode',Worklet);const ctx:any={currentTime:0,sampleRate:48000,destination:new Node(),audioWorklet:{addModule:async()=>{}},createGain:()=>new Node(),createStereoPanner:()=>new Node(),createAnalyser:()=>new Node()};
 const mixer=createMixer(ctx,new Node() as any);let project=addTrack(createProject(),'A','a');const mix=withFxView(normalizeMix(),{reverb:{...fxView(normalizeMix()).reverb,wet:.5}});project={...project,tracks:project.tracks.map(t=>({...t,mix}))};mixer.sync(project);await new Promise(r=>setTimeout(r,0));const fx=processors.find(p=>p.name==='sa3-reverb');fx.port.onmessage({data:{type:'error',message:'allocation failed'}});expect(mixer.error('a')).toContain('allocation failed');mixer.retry('a');await new Promise(r=>setTimeout(r,0));expect(mixer.error('a')).toContain('allocation failed');expect(fx.messages.filter((m:any)=>m.type==='module')).toHaveLength(2);expect(fx.messages.find((m:any)=>m.type==='module').bytes).toBeInstanceOf(ArrayBuffer);fx.port.onmessage({data:{type:'ready',algorithm:'hall'}});expect(mixer.error('a')).toBeNull();vi.unstubAllGlobals();
});

it('editing pan while reverb loads does not invalidate or strand initialization',async()=>{
 let resolve!:(m:ArrayBuffer)=>void;loading.pending=new Promise(r=>resolve=r);const processors:any[]=[];class Node {gain={value:1,setTargetAtTime(){},cancelScheduledValues(){},setValueAtTime(){},linearRampToValueAtTime(){}};pan={value:0,setTargetAtTime(){}};connect(){}disconnect(){}addEventListener(){}getFloatFrequencyData(a:Float32Array){a.fill(-100);}}class Worklet extends Node {name:string;messages:any[]=[];port={onmessage:null as any,postMessage:(m:any)=>this.messages.push(m),close(){}};constructor(_c:any,name:string){super();this.name=name;processors.push(this);}}vi.stubGlobal('AudioWorkletNode',Worklet);
 const ctx:any={currentTime:0,sampleRate:48000,destination:new Node(),audioWorklet:{addModule:async()=>{}},createGain:()=>new Node(),createStereoPanner:()=>new Node(),createAnalyser:()=>new Node()},mixer=createMixer(ctx,new Node() as any);let p=addTrack(createProject(),'A','a');let mix=withFxView(normalizeMix(),{reverb:{...fxView(normalizeMix()).reverb,wet:.5}});p={...p,tracks:p.tracks.map(t=>({...t,mix}))};mixer.sync(p);await new Promise(r=>setTimeout(r,0));mix={...mix,pan:.2};mixer.sync({...p,tracks:p.tracks.map(t=>({...t,mix}))});await new Promise(r=>setTimeout(r,0));resolve(new Uint8Array([0,97,115,109,1,0,0,0]).buffer);await new Promise(r=>setTimeout(r,0));const fx=processors.find(n=>n.name==='sa3-reverb');expect(fx.messages.filter((m:any)=>m.type==='module')).toHaveLength(1);loading.pending=null;vi.unstubAllGlobals();
});

it('builds distinct ordered insert nodes and disposes a removed plugin',async()=>{
 const nodes:any[]=[];class Node {connections:any[]=[];gain={value:1,setTargetAtTime:vi.fn(),cancelScheduledValues(){},setValueAtTime(){},linearRampToValueAtTime(){}};pan={value:0,setTargetAtTime(){}};connect(n:any){this.connections.push(n);return n;}disconnect(target?:any){this.connections=target?this.connections.filter(n=>n!==target):[];}addEventListener(){}getFloatFrequencyData(a:Float32Array){a.fill(-100);}}class Worklet extends Node {name:string;messages:any[]=[];port={onmessage:null as any,postMessage:(m:any)=>this.messages.push(m),close:vi.fn()};constructor(_c:any,name:string){super();this.name=name;nodes.push(this);}}vi.stubGlobal('AudioWorkletNode',Worklet);
 const ctx:any={currentTime:0,sampleRate:48000,destination:new Node(),audioWorklet:{addModule:async()=>{}},createGain:()=>new Node(),createStereoPanner:()=>new Node(),createAnalyser:()=>new Node()},mixer=createMixer(ctx,new Node() as any);let p=addTrack(createProject(),'A','a');const mix=normalizeMix({plugins:[{id:'eq1',type:'eq'},{id:'verb',type:'reverb',settings:{wet:.5}},{id:'eq2',type:'eq'}]});p={...p,tracks:p.tracks.map(t=>({...t,mix}))};mixer.sync(p);await new Promise(r=>setTimeout(r,60));const plugins=nodes.filter(n=>n.name!=='sa3-meter');expect(plugins.map(n=>n.name)).toEqual(['sa3-eq','sa3-reverb','sa3-eq']);const connected=(a:any,b:any,seen=new Set<any>()):boolean=>a===b||(!seen.has(a)&&(seen.add(a),a.connections.some((n:any)=>connected(n,b,seen))));expect(connected(plugins[0],plugins[1])).toBe(true);expect(connected(plugins[1],plugins[2])).toBe(true);expect(mixer.spectrum('a','eq1')).not.toBeNull();expect(mixer.spectrum('a','eq2')).not.toBeNull();expect(mixer.spectrum('a','verb')).toBeNull();expect(mixer.spectrum('a','')).not.toBeNull();mixer.listen('a','eq2',{...makeBand('a'),freq:700});expect(plugins[2].messages.some((m:any)=>m.type==='listen'&&m.band?.freq===700)).toBe(true);
 mixer.sync({...p,tracks:p.tracks.map(t=>({...t,mix:{...mix,plugins:[mix.plugins[2]!,mix.plugins[0]!]}}))});await new Promise(r=>setTimeout(r,60));expect(plugins[1].messages.some((m:any)=>m.type==='dispose')).toBe(true);expect(plugins[1].port.close).toHaveBeenCalled();expect(nodes.filter(n=>n.name==='sa3-eq')).toHaveLength(2);expect(connected(plugins[2],plugins[0])).toBe(true);expect(connected(plugins[0],plugins[2])).toBe(false);expect(mixer.spectrum('a','eq1')).not.toBeNull();vi.unstubAllGlobals();
});

it('does not attach a reverb module after its track is removed during loading',async()=>{
 let resolve!:(m:ArrayBuffer)=>void;loading.pending=new Promise(r=>resolve=r);const nodes:any[]=[];
 class Node {gain={value:1,setTargetAtTime(){},cancelScheduledValues(){},setValueAtTime(){},linearRampToValueAtTime(){}};pan={setTargetAtTime(){}};connect(){}disconnect(){}addEventListener(){}getFloatFrequencyData(){} }
 class Worklet extends Node {name:string;messages:any[]=[];port={onmessage:null as any,postMessage:(m:any)=>this.messages.push(m),close:vi.fn()};constructor(_c:any,name:string){super();this.name=name;nodes.push(this);}}
 vi.stubGlobal('AudioWorkletNode',Worklet);const ctx:any={currentTime:0,sampleRate:48000,destination:new Node(),audioWorklet:{addModule:async()=>{}},createGain:()=>new Node(),createStereoPanner:()=>new Node(),createAnalyser:()=>new Node()},mixer=createMixer(ctx,new Node() as any),empty=createProject(),p=addTrack(empty,'A','a');mixer.sync({...p,tracks:p.tracks.map(t=>({...t,mix:normalizeMix({plugins:[{id:'r',type:'reverb',settings:{wet:1}}]})}))});await new Promise(r=>setTimeout(r,0));mixer.sync(empty);resolve(new ArrayBuffer(8));await new Promise(r=>setTimeout(r,0));const reverb=nodes.find(n=>n.name==='sa3-reverb');expect(reverb.messages.filter((m:any)=>m.type==='module')).toHaveLength(0);expect(reverb.port.close).toHaveBeenCalled();loading.pending=null;vi.unstubAllGlobals();
});

it('fades structural changes over twenty milliseconds before rewiring',async()=>{
 vi.useFakeTimers();const gains:any[]=[];class Node {gain={value:1,setTargetAtTime(){},cancelScheduledValues(){},setValueAtTime:vi.fn(),linearRampToValueAtTime:vi.fn()};pan={setTargetAtTime(){}};connections:any[]=[];connect(n:any){this.connections.push(n);}disconnect(){this.connections=[];}addEventListener(){}getFloatFrequencyData(){} }
 class Worklet extends Node {port={onmessage:null as any,postMessage(){},close(){}};constructor(_c:any,_name:string){super();}}
 vi.stubGlobal('AudioWorkletNode',Worklet);const ctx:any={currentTime:2,state:'running',sampleRate:48000,destination:new Node(),audioWorklet:{addModule:async()=>{}},createGain:()=>{const n=new Node();gains.push(n);return n;},createStereoPanner:()=>new Node(),createAnalyser:()=>new Node()},mixer=createMixer(ctx,new Node() as any);let p=addTrack(createProject(),'A','a');mixer.sync(p);await vi.advanceTimersByTimeAsync(0);const mix=normalizeMix({plugins:[{id:'eq',type:'eq'}]});p={...p,tracks:p.tracks.map(t=>({...t,mix}))};mixer.sync(p);const fade=gains[1].gain;expect(fade.linearRampToValueAtTime).toHaveBeenLastCalledWith(0,2.02);expect(mixer.spectrum('a','eq')).toBeNull();await vi.advanceTimersByTimeAsync(24);expect(mixer.spectrum('a','eq')).toBeNull();await vi.advanceTimersByTimeAsync(1);expect(mixer.spectrum('a','eq')).toBeNull();ctx.currentTime=2.025;await vi.advanceTimersByTimeAsync(5);expect(mixer.spectrum('a','eq')).not.toBeNull();expect(fade.linearRampToValueAtTime).toHaveBeenLastCalledWith(1,2.045);ctx.state='suspended';mixer.sync({...p,tracks:p.tracks.map(t=>({...t,mix:{...mix,plugins:[]}}))});await vi.advanceTimersByTimeAsync(25);expect(fade.setValueAtTime).toHaveBeenCalledWith(0,2.025);expect(mixer.spectrum('a','eq')).toBeNull();vi.useRealTimers();vi.unstubAllGlobals();
});

it('requests Hall again when returning from Plate even if its ready acknowledgement is still in transit',async()=>{
 const nodes:any[]=[];class Node {connect(){}disconnect(){}addEventListener(){} }class Worklet extends Node {messages:any[]=[];port={onmessage:null as any,postMessage:(m:any)=>this.messages.push(m),close(){}};constructor(_ctx:any,_name:string){super();nodes.push(this);}}
 vi.stubGlobal('AudioWorkletNode',Worklet);const {pluginNodeFactories}=await import('./pluginNodes'),ctx:any={sampleRate:48000,createGain:()=>new Node()},hall=normalizeMix({plugins:[{id:'r',type:'reverb',settings:{wet:1,algorithm:'hall'}}]}).plugins[0]!,plate=normalizeMix({plugins:[{id:'r',type:'reverb',settings:{wet:1,algorithm:'plate'}}]}).plugins[0]!,plugin=pluginNodeFactories.reverb(ctx,hall);await new Promise(r=>setTimeout(r,0));nodes[0].port.onmessage({data:{type:'ready',algorithm:'hall'}});plugin.update(plate);await new Promise(r=>setTimeout(r,0));plugin.update(hall);await new Promise(r=>setTimeout(r,0));expect(nodes[0].messages.filter((m:any)=>m.type==='module').map((m:any)=>m.algorithm)).toEqual(['hall','plate','hall']);plugin.dispose();vi.unstubAllGlobals();
});

it('upmixes mono sources to stable dual-mono stereo before both empty and populated plugin chains',async()=>{
 class Node {channelCount=2;channelCountMode='max';gain={value:1,setTargetAtTime(){},cancelScheduledValues(){},setValueAtTime(){},linearRampToValueAtTime(){}};pan={setTargetAtTime(){}};connect(){}disconnect(){}addEventListener(){}getFloatFrequencyData(){} }
 class Worklet extends Node {port={onmessage:null as any,postMessage(){},close(){}};constructor(_ctx:any,_name:string){super();}}
 vi.stubGlobal('AudioWorkletNode',Worklet);const ctx:any={currentTime:0,sampleRate:48000,destination:new Node(),audioWorklet:{addModule:async()=>{}},createGain:()=>new Node(),createStereoPanner:()=>new Node(),createAnalyser:()=>new Node()},mixer=createMixer(ctx,new Node() as any);const p=addTrack(createProject(),'A','a');mixer.sync(p);const input=mixer.input('a');expect(input.channelCount).toBe(2);expect(input.channelCountMode).toBe('explicit');mixer.sync({...p,tracks:p.tracks.map(t=>({...t,mix:normalizeMix({plugins:[{id:'eq',type:'eq'}]})}))});await new Promise(r=>setTimeout(r,0));expect(mixer.input('a')).toBe(input);expect(input.channelCountMode).toBe('explicit');vi.unstubAllGlobals();
});
