import {it,expect,vi} from 'vitest';
const loading=vi.hoisted(()=>({pending:null as Promise<WebAssembly.Module>|null}));
vi.mock('./dragonfly',()=>({loadDragonfly:async()=>loading.pending??new WebAssembly.Module(new Uint8Array([0,97,115,109,1,0,0,0]))}));
import {createMixer} from './controller';import {createProject,addTrack} from '../../store/projectModel';import {normalizeMix} from './model';
it('failed reverb initialization remains visible and retry waits for confirmed readiness',async()=>{
 const processors:any[]=[];class Node {gain={value:1,setTargetAtTime(){}};pan={value:0,setTargetAtTime(){}};fftSize=2048;smoothingTimeConstant=0;connect(){}disconnect(){}addEventListener(){}getFloatFrequencyData(a:Float32Array){a.fill(-100);}}
 class Worklet extends Node {name:string;messages:any[]=[];port={onmessage:null as any,postMessage:(m:any)=>this.messages.push(m),close(){}};constructor(_c:any,name:string){super();this.name=name;processors.push(this);}}
 vi.stubGlobal('AudioWorkletNode',Worklet);const ctx:any={currentTime:0,sampleRate:48000,destination:new Node(),audioWorklet:{addModule:async()=>{}},createGain:()=>new Node(),createStereoPanner:()=>new Node(),createAnalyser:()=>new Node()};
 const mixer=createMixer(ctx,new Node() as any);let project=addTrack(createProject(),'A','a');const mix=normalizeMix();mix.reverb.wet=.5;project={...project,tracks:project.tracks.map(t=>({...t,mix}))};mixer.sync(project);await new Promise(r=>setTimeout(r,0));const fx=processors.find(p=>p.name==='sa3-track-fx');fx.port.onmessage({data:{type:'error',message:'allocation failed'}});expect(mixer.error('a')).toContain('allocation failed');mixer.retry('a');await new Promise(r=>setTimeout(r,0));expect(mixer.error('a')).toContain('allocation failed');expect(fx.messages.filter((m:any)=>m.type==='module')).toHaveLength(2);fx.port.onmessage({data:{type:'ready',algorithm:'hall'}});expect(mixer.error('a')).toBeNull();vi.unstubAllGlobals();
});

it('editing pan while reverb loads does not invalidate or strand initialization',async()=>{
 let resolve!:(m:WebAssembly.Module)=>void;loading.pending=new Promise(r=>resolve=r);const processors:any[]=[];class Node {gain={value:1,setTargetAtTime(){}};pan={value:0,setTargetAtTime(){}};connect(){}disconnect(){}addEventListener(){}getFloatFrequencyData(a:Float32Array){a.fill(-100);}}class Worklet extends Node {name:string;messages:any[]=[];port={onmessage:null as any,postMessage:(m:any)=>this.messages.push(m),close(){}};constructor(_c:any,name:string){super();this.name=name;processors.push(this);}}vi.stubGlobal('AudioWorkletNode',Worklet);
 const ctx:any={currentTime:0,sampleRate:48000,destination:new Node(),audioWorklet:{addModule:async()=>{}},createGain:()=>new Node(),createStereoPanner:()=>new Node(),createAnalyser:()=>new Node()},mixer=createMixer(ctx,new Node() as any);let p=addTrack(createProject(),'A','a');const mix=normalizeMix();mix.reverb.wet=.5;p={...p,tracks:p.tracks.map(t=>({...t,mix}))};mixer.sync(p);await new Promise(r=>setTimeout(r,0));mix.pan=.2;mixer.sync({...p,tracks:p.tracks.map(t=>({...t,mix}))});await new Promise(r=>setTimeout(r,0));resolve(new WebAssembly.Module(new Uint8Array([0,97,115,109,1,0,0,0])));await new Promise(r=>setTimeout(r,0));const fx=processors.find(n=>n.name==='sa3-track-fx');expect(fx.messages.filter((m:any)=>m.type==='module')).toHaveLength(1);loading.pending=null;vi.unstubAllGlobals();
});
