import {describe,it,expect} from 'vitest';
import {sections,responseDb,EqProcessor} from './eq';
import {makeBand,dbGain} from './model';import {normalizeMix,fxView} from './plugins';
describe('mixer EQ',()=>{
 it('legacy and corrupt settings stay finite and initially dry',()=>{const m=fxView(normalizeMix());expect(m.volumeDb).toBe(0);expect(m.pan).toBe(0);expect(m.reverb.wet).toBe(0);expect(m.eq.bands).toEqual([]);const x=fxView(normalizeMix({volumeDb:Infinity,pan:4,eq:{bands:[{...makeBand('a'),freq:-4,q:Infinity,gain:100}]}} as never));expect(x.volumeDb).toBe(0);expect(x.pan).toBe(1);expect(x.eq.bands[0]!.freq).toBe(20);expect(x.eq.bands[0]!.gain).toBe(24);expect(Number.isFinite(x.eq.bands[0]!.q)).toBe(true);});
 for(const sr of [44100,48000])it(`bell response and actual rendered gain agree at ${sr}`,()=>{const b={...makeBand('a'),freq:1000,gain:12,q:3};const s=sections(b,sr);expect(responseDb(s,1000,sr)).toBeCloseTo(12,5);const p=new EqProcessor(sr);p.set({bypass:false,trimDb:0,bands:[b]});const input=Float32Array.from({length:sr},(_,i)=>.01*Math.sin(2*Math.PI*1000*i/sr));const out=new Float32Array(sr);p.process(input,input,out,new Float32Array(sr));let a=0,c=0;for(let i=sr/2|0;i<sr;i++){a+=input[i]!**2;c+=out[i]!**2;}expect(10*Math.log10(c/a)).toBeCloseTo(12,1);});
 it('shelf Q changes shape while keeping endpoint gain',()=>{const b={...makeBand('a'),type:'lowShelf' as const,freq:1000,gain:12};expect(responseDb(sections(b,48000),20,48000)).toBeCloseTo(12,1);expect(Math.abs(responseDb(sections({...b,q:5},48000),700,48000)-responseDb(sections({...b,q:.5},48000),700,48000))).toBeGreaterThan(2);});
 it('cut order controls attenuation independently of gain',()=>{const b={...makeBand('a'),type:'lowPass' as const,freq:500};expect(responseDb(sections({...b,slope:48},48000),2000,48000)).toBeLessThan(-85);expect(responseDb(sections({...b,slope:6},48000),2000,48000)).toBeGreaterThan(-15);});
 it('notch rejects center and all-pass keeps magnitude',()=>{for(const type of ['notch','allPass'] as const){const b={...makeBand('a'),type,freq:1000,q:4};const db=responseDb(sections(b,48000),1000,48000);expect(type==='notch'?db<-90:Math.abs(db)<1e-8).toBe(true);}});
 it('disabled and bypass filters preserve the signal and output trim is independent',()=>{const p=new EqProcessor(48000);p.set({bypass:true,trimDb:-6,bands:[{...makeBand('a'),gain:24}]});const a=new Float32Array(4800).fill(.1),out=new Float32Array(a.length);p.process(a,a,out,new Float32Array(a.length));expect(out[4799]).toBeCloseTo(.1*dbGain(-6),5);});
});
it('unchanged EQ and trim edits preserve the settled narrow-filter history',()=>{const eq={bypass:false,trimDb:0,bands:[{...makeBand('a'),freq:40,gain:20,q:30}]},a=new EqProcessor(48000),b=new EqProcessor(48000);a.set(eq);b.set(eq);const input=Float32Array.from({length:48000},(_,i)=>.01*Math.sin(2*Math.PI*40*i/48000));const al=new Float32Array(48000),bl=new Float32Array(48000);a.process(input,input,al,new Float32Array(48000));b.process(input,input,bl,new Float32Array(48000));a.set({...eq,trimDb:-6});const next=input.slice(0,128),outA=new Float32Array(128),outB=new Float32Array(128);a.process(next,next,outA,new Float32Array(128));b.process(next,next,outB,new Float32Array(128));expect(Math.abs(outA[0]!/outB[0]!)).toBeGreaterThan(.99);expect(Math.abs(outA[127]!/outB[127]!)).toBeGreaterThan(.85);});
