import {it,expect,vi} from 'vitest';import {readFileSync} from 'node:fs';import {normalizeMix,fxView} from './plugins';
it('a failed algorithm replacement preserves the working Dragonfly instance',async()=>{
 vi.resetModules();let C:any;const messages:any[]=[];vi.stubGlobal('sampleRate',48000);vi.stubGlobal('AudioWorkletProcessor',class {port={onmessage:null as any,postMessage:(m:any)=>messages.push(m)};});vi.stubGlobal('registerProcessor',(name:string,c:any)=>{if(name==='sa3-track-fx')C=c;});await import('./processor');const module=new WebAssembly.Module(readFileSync('public/dragonfly/hall.wasm')),mix=fxView(normalizeMix());mix.reverb.wet=1;const p=new C({processorOptions:{mix,module,algorithm:'hall'}});const l=new Float32Array(128),r=new Float32Array(128),outL=new Float32Array(128),outR=new Float32Array(128);l[0]=1;p.process([[l,r]],[[outL,outR]]);await p.port.onmessage({data:{type:'module',bytes:new Uint8Array([0,97,115,109,1,0,0,0]).buffer,algorithm:'plate'}});expect(messages.some(m=>m.type==='error')).toBe(true);l.fill(0);expect(()=>{for(let i=0;i<50;i++)p.process([[l,r]],[[outL,outR]]);}).not.toThrow();expect(outL.every(Number.isFinite)).toBe(true);vi.unstubAllGlobals();
});
it('bypassed reverb does not resume a frozen tail when enabled again',async()=>{
 vi.resetModules();let C:any;vi.stubGlobal('sampleRate',48000);vi.stubGlobal('AudioWorkletProcessor',class {port={onmessage:null as any,postMessage(){}};});vi.stubGlobal('registerProcessor',(name:string,c:any)=>{if(name==='sa3-track-fx')C=c;});await import('./processor');const module=new WebAssembly.Module(readFileSync('public/dragonfly/hall.wasm')),mix=fxView(normalizeMix());mix.reverb.wet=1;const p=new C({processorOptions:{mix,module,algorithm:'hall'}}),l=new Float32Array(128),r=new Float32Array(128),ol=new Float32Array(128),or=new Float32Array(128);l[0]=1;for(let i=0;i<100;i++){p.process([[l,r]],[[ol,or]]);l.fill(0);}mix.reverb.bypass=true;p.port.onmessage({data:{type:'mix',mix:structuredClone(mix)}});for(let i=0;i<500;i++)p.process([[l,r]],[[ol,or]]);mix.reverb.bypass=false;p.port.onmessage({data:{type:'mix',mix}});let peak=0;for(let i=0;i<100;i++){p.process([[l,r]],[[ol,or]]);for(const x of ol)peak=Math.max(peak,Math.abs(x));}expect(peak).toBeLessThan(1e-6);vi.unstubAllGlobals();
});
it('a module message carries wasm bytes, compiled inside the worklet, and yields a reverb tail',async()=>{
 vi.resetModules();let C:any;const messages:any[]=[];vi.stubGlobal('sampleRate',48000);vi.stubGlobal('AudioWorkletProcessor',class {port={onmessage:null as any,postMessage:(m:any)=>messages.push(m)};});vi.stubGlobal('registerProcessor',(name:string,c:any)=>{if(name==='sa3-track-fx')C=c;});await import('./processor');
 const bytes=Uint8Array.from(readFileSync('public/dragonfly/hall.wasm')).buffer,mix=fxView(normalizeMix());mix.reverb.wet=1;const p=new C({processorOptions:{mix}}),l=new Float32Array(128),r=new Float32Array(128),ol=new Float32Array(128),or=new Float32Array(128);
 await p.port.onmessage({data:{type:'module',bytes,algorithm:'hall'}});expect(messages.filter(m=>m.type==='ready')).toEqual([{type:'ready',algorithm:'hall'}]);expect(messages.some(m=>m.type==='error')).toBe(false);
 l[0]=1;let tail=0;for(let i=0;i<200;i++){p.process([[l,r]],[[ol,or]]);l.fill(0);if(i>60)for(const x of ol)tail+=x*x;}expect(tail).toBeGreaterThan(1e-8);vi.unstubAllGlobals();
});
