<script lang="ts">
 import {updateProject} from '../appState.svelte';import {toggleMute,toggleSolo,type Track} from '../../store/projectModel';
 import {normalizeMix,type PluginInstance} from '../../audio/mixer/plugins';import KnobDial from '../../components/KnobDial.svelte';import Meter from '../Meter.svelte';import VolumeFader from '../VolumeFader.svelte';import PluginStack from './PluginStack.svelte';
 let {track,color,onedit,onadd,error=null,onretry}:{track:Track;color:string;onedit:(p:PluginInstance)=>void;onadd:()=>void;error?:string|null;onretry:()=>void}=$props();
 const mix=$derived(normalizeMix(track.mix));
 function balance(patch:{volumeDb?:number;pan?:number}){updateProject(p=>({...p,tracks:p.tracks.map(t=>t.id===track.id?{...t,mix:normalizeMix({...normalizeMix(t.mix),...patch})}:t)}));}
 const panLabel=$derived(mix.pan===0?'Center':`${Math.round(Math.abs(mix.pan)*100)}% ${mix.pan<0?'L':'R'}`);
</script>
<section class="channel-strip" id="mix-{track.id}" data-track-id={track.id} style="--channel:{color}" aria-label="{track.name} channel">
 <header><strong>{track.name}</strong><div class="balance"><div class="switches"><button class:active={track.muted} aria-label="Mute {track.name}" aria-pressed={track.muted} onclick={()=>updateProject(p=>toggleMute(p,track.id))}>M</button><button class:active={track.solo} aria-label="Solo {track.name}" aria-pressed={!!track.solo} onclick={()=>updateProject(p=>toggleSolo(p,track.id))}>S</button></div><div class="pan"><KnobDial value={mix.pan} min={-1} max={1} size={28} label="Pan {track.name}" on:change={e=>balance({pan:e.detail.value})}/><span>{panLabel}</span></div><div class="pan-buttons"><button aria-label="Pan {track.name} left" onclick={()=>balance({pan:Math.max(-1,mix.pan-.1)})}>L</button><button aria-label="Center pan {track.name}" onclick={()=>balance({pan:0})}>C</button><button aria-label="Pan {track.name} right" onclick={()=>balance({pan:Math.min(1,mix.pan+.1)})}>R</button></div></div></header>
 <div class="channel-body"><PluginStack trackId={track.id} plugins={mix.plugins} {onedit} {onadd}/><div class="levels"><VolumeFader label="{track.name} volume" value={mix.volumeDb} onchange={v=>balance({volumeDb:v})}/><Meter trackId={track.id} vertical/></div></div>
 {#if error}<div class="error" role="alert"><span>{error}</span><button onclick={onretry}>Retry effects</button></div>{/if}
</section>
<style>.channel-strip{width:300px;max-width:calc(100vw - 20px);height:100%;flex:none;scroll-snap-align:start;border:1px solid var(--line);border-top:3px solid var(--channel);border-radius:12px;background:var(--panel);padding:10px;display:flex;flex-direction:column;overflow:hidden}header{height:113px;flex:none}header strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:15px;height:26px}.balance{display:flex;gap:5px;justify-content:space-between;align-items:center}.switches{display:flex;gap:5px}.switches button{width:40px;height:44px;background:var(--panel2);border-radius:7px;font-weight:700}.switches .active{color:var(--sa3);background:var(--sa3bg)}.pan{display:flex;flex-direction:column;align-items:center;gap:3px}.pan span{font-size:10px;color:var(--dim);white-space:nowrap}.pan-buttons{display:grid;grid-template-columns:repeat(3,40px);gap:2px}.pan-buttons button{height:40px;background:var(--panel2);border-radius:5px;font-size:11px}.channel-body{flex:1;min-height:0;display:grid;grid-template-columns:minmax(0,1fr) 124px;gap:8px}.levels{height:100%;min-height:0;display:flex;gap:4px}.error{max-height:64px;flex:none;font-size:10px;color:#ff7878;overflow:auto;overflow-wrap:anywhere}.error button{height:40px;width:100%;background:var(--panel2);border-radius:6px;color:var(--text)}</style>
